[options]
# Reverse the order of entries so the relevant ones are at the bottom
BottomUp
# Periodically call sudo in the background to prevent timeouts during long builds
SudoLoop
# Print new news during sysupgrade.
NewsOnUpgrade
# Show a detailed list of updates in a similar format to pacman's VerbosePkgLists option.
UpgradeMenu
