[options]
# reverse the order of entries so the relevant ones are at the bottom
BottomUp
# periodically call sudo in the background to prevent timeouts during long builds
SudoLoop
# print new news during sysupgrade.
NewsOnUpgrade